name: Publish latest reviews feed

on:
  workflow_dispatch:     # allows manual runs
  schedule:
    - cron: "0 * * * *"  # runs every hour

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create sample feed
        run: |
          mkdir -p data
          echo '{
            "generated_at": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'",
            "window_days": 30,
            "reviews": []
          }' > data/latest.json
          cp data/latest.json data/latest.csv

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/latest.json data/latest.csv
          git commit -m "Update latest feed" || echo "No changes"
          git push
